# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("message.proto", :syntax => :proto3) do
    add_message "Tag" do
      optional :id, :int64, 1
      optional :name, :string, 2
    end
    add_message "Message" do
      optional :name, :string, 1
      optional :priority, :enum, 2, "Message.Priority"
      repeated :tags, :message, 3, "Tag"
    end
    add_enum "Message.Priority" do
      value :HIGH, 0
      value :LOW, 1
    end
  end
end

Tag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tag").msgclass
Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message").msgclass
Message::Priority = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Message.Priority").enummodule
